"""
Column mapping and schema definitions
"""

# Unified schema for all datasets
UNIFIED_SCHEMA = [
    'self_employed', 'no_employees', 'tech_company', 'primary_role_tech', 'benefits',
    'know_options', 'formal_discussion', 'resources', 'anonymity',
    'leave_ease', 'comfort_physical_mental', 'comfort_supervisor', 'discussed_with_employer',
    'comfort_coworkers', 'discussed_with_coworkers', 'coworker_discussed_with_you',
    'employer_importance_physical', 'employer_importance_mental', 'coverage_mental_health',
    'know_resources', 'reveal_to_clients', 'reveal_to_coworkers',
    'productivity_affected', 'productivity_percent_affected', 'have_prev_employers',
    'prev_tech_company', 'prev_benefits', 'prev_know_options',
    'prev_formal_discussion', 'prev_resources', 'prev_anonymity',
    'prev_comfort_physical_mental', 'prev_comfort_supervisor', 'prev_discussed_with_employer',
    'prev_comfort_coworkers', 'prev_discussed_with_coworkers',
    'prev_employer_importance_physical', 'prev_employer_importance_mental',
    'currently_disordered', 'diagnosed_disorder', 'disorder_anxiety', 'disorder_mood',
    'disorder_psychotic', 'disorder_eating', 'disorder_adh_add',
    'disorder_personality', 'disorder_ocd', 'disorder_ptsd',
    'disorder_stress_response', 'disorder_dissociative', 'disorder_substance_use',
    'disorder_addictive', 'disorder_other', 'past_disorder', 'sought_treatment',
    'family_history', 'interference_when_treated', 'interference_when_not_treated',
    'observations_less_likely_reveal', 'share_with_friends_family',
    'bring_up_physical_interview', 'bring_up_physical_why', 'bring_up_mental_interview',
    'bring_up_mental_why', 'openly_identified', 'identified_affected_career',
    'identified_affected_how', 'team_reaction_if_knew', 'observed_unsupportive_response',
    'unsupportive_response_desc', 'observed_supportive_response', 'supportive_response_desc',
    'industry_support_rating', 'improvement_suggestions', 'additional_comments',
    'willing_to_interview', 'age', 'gender', 'country_live',
    'state_live', 'race', 'country_work', 'state_work'
]

# Column mapping for different file versions
COLUMN_MAP = {
    # survey.csv (2014-2016)
    'self_employed': 'self_employed',
    'no_employees': 'no_employees',
    'tech_company': 'tech_company',
    'benefits': 'benefits',
    'care_options': 'know_options',
    'wellness_program': 'formal_discussion',
    'seek_help': 'resources',
    'anonymity': 'anonymity',
    'leave': 'leave_ease',
    'coworkers': 'comfort_coworkers',
    'supervisor': 'comfort_supervisor',
    'mental_health_consequence': 'discussed_with_employer',
    'mental_vs_physical': 'comfort_physical_mental',
    'obs_consequence': 'observations_less_likely_reveal',
    'family_history': 'family_history',
    'treatment': 'sought_treatment',
    'work_interfere': 'interference_when_treated',
    
    # OSMI 2017+
    '*Are you self-employed?*': 'self_employed',
    'How many employees does your company or organization have?': 'no_employees',
    'Is your employer primarily a tech company/organization?': 'tech_company',
    'Is your primary role within your company related to tech/IT?': 'primary_role_tech',
    'Does your employer provide mental health benefits as part of healthcare coverage?': 'benefits',
    'Do you know the options for mental health care available under your employer-provided health coverage?': 'know_options',
    'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?': 'formal_discussion',
    'Does your employer offer resources to learn more about mental health disorders and options for seeking help?': 'resources',
    'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?': 'anonymity',
    'If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?': 'leave_ease',
    'Would you feel more comfortable talking to your coworkers about your physical health or your mental health?': 'comfort_physical_mental',
    'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?': 'comfort_supervisor',
    'Have you ever discussed your mental health with your employer?': 'discussed_with_employer',
    'Would you feel comfortable discussing a mental health issue with your coworkers?': 'comfort_coworkers',
    'Have you ever discussed your mental health with coworkers?': 'discussed_with_coworkers',
    'Have you ever had a coworker discuss their or another coworker\'s mental health with you?': 'coworker_discussed_with_you',
    'Overall, how much importance does your employer place on physical health?': 'employer_importance_physical',
    'Overall, how much importance does your employer place on mental health?': 'employer_importance_mental',
    'Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?': 'coverage_mental_health',
    'Do you know local or online resources to seek help for a mental health issue?': 'know_resources',
    'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?': 'reveal_to_clients',
    'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?': 'reveal_to_coworkers',
    'Do you believe your productivity is ever affected by a mental health issue?': 'productivity_affected',
    'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?': 'productivity_percent_affected',
    'Do you have previous employers?': 'have_prev_employers',
    'Was your employer primarily a tech company/organization?': 'prev_tech_company',
    'Have your previous employers provided mental health benefits?': 'prev_benefits',
    'Were you aware of the options for mental health care provided by your previous employers?': 'prev_know_options',
    'Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?': 'prev_formal_discussion',
    'Did your previous employers provide resources to learn more about mental health disorders and how to seek help?': 'prev_resources',
    'Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?': 'prev_anonymity',
    'Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?': 'prev_comfort_physical_mental',
    'Would you have been willing to discuss your mental health with your direct supervisor(s)?': 'prev_comfort_supervisor',
    'Did you ever discuss your mental health with your previous employer?': 'prev_discussed_with_employer',
    'Would you have been willing to discuss your mental health with your coworkers at previous employers?': 'prev_comfort_coworkers',
    'Did you ever discuss your mental health with a previous coworker(s)?': 'prev_discussed_with_coworkers',
    'Overall, how much importance did your previous employer place on physical health?': 'prev_employer_importance_physical',
    'Overall, how much importance did your previous employer place on mental health?': 'prev_employer_importance_mental',
    'Do you currently have a mental health disorder?': 'currently_disordered',
    'Have you ever been diagnosed with a mental health disorder?': 'diagnosed_disorder',
    'Anxiety Disorder (Generalized, Social, Phobia, etc)': 'disorder_anxiety',
    'Mood Disorder (Depression, Bipolar Disorder, etc)': 'disorder_mood',
    'Psychotic Disorder (Schizophrenia, Schizoaffective, etc)': 'disorder_psychotic',
    'Eating Disorder (Anorexia, Bulimia, etc)': 'disorder_eating',
    'Attention Deficit Hyperactivity Disorder': 'disorder_adh_add',
    'Personality Disorder (Borderline, Antisocial, Paranoid, etc)': 'disorder_personality',
    'Obsessive-Compulsive Disorder': 'disorder_ocd',
    'Post-Traumatic Stress Disorder': 'disorder_ptsd',
    'Stress Response Syndromes': 'disorder_stress_response',
    'Dissociative Disorder': 'disorder_dissociative',
    'Substance Use Disorder': 'disorder_substance_use',
    'Addictive Disorder': 'disorder_addictive',
    'Other': 'disorder_other',
    'Have you had a mental health disorder in the past?': 'past_disorder',
    'Have you ever sought treatment for a mental health disorder from a mental health professional?': 'sought_treatment',
    'Do you have a family history of mental illness?': 'family_history',
    'If you have a mental health disorder, how often do you feel that it interferes with your work when being treated effectively?': 'interference_when_treated',
    'If you have a mental health disorder, how often do you feel that it interferes with your work when NOT being treated effectively (i.e., when you are experiencing symptoms)?': 'interference_when_not_treated',
    'Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?': 'observations_less_likely_reveal',
    'How willing would you be to share with friends and family that you have a mental illness?': 'share_with_friends_family',
    'Would you be willing to bring up a physical health issue with a potential employer in an interview?': 'bring_up_physical_interview',
    'Why or why not?': 'bring_up_physical_why',
    'Would you bring up your mental health with a potential employer in an interview?': 'bring_up_mental_interview',
    'Why or why not?': 'bring_up_mental_why',
    'Are you openly identified at work as a person with a mental health issue?': 'openly_identified',
    'Has being identified as a person with a mental health issue affected your career?': 'identified_affected_career',
    'How has it affected your career?': 'identified_affected_how',
    'If they knew you suffered from a mental health disorder, how do you think that team members/co-workers would react?': 'team_reaction_if_knew',
    'Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?': 'observed_unsupportive_response',
    'Describe the circumstances of the badly handled or unsupportive response.': 'unsupportive_response_desc',
    'Have you observed or experienced supportive or well handled response to a mental health issue in your current or previous workplace?': 'observed_supportive_response',
    'Describe the circumstances of the supportive or well handled response.': 'supportive_response_desc',
    'Overall, how well do you think the tech industry supports employees with mental health issues?': 'industry_support_rating',
    'Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.': 'improvement_suggestions',
    'If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.': 'additional_comments',
    'Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used anonymously and only with your permission.)': 'willing_to_interview',
    'What is your age?': 'age',
    'What is your gender?': 'gender',
    'What country do you live in?': 'country_live',
    'What US state or territory do you live in?': 'state_live',
    'What is your race?': 'race',
    'What country do you work in?': 'country_work',
    'What US state or territory do you work in?': 'state_work',
}

# Dataset name patterns for identification
DATASET_PATTERNS = {
    'survey_2014_2016': ['survey.csv'],
    'osmi_2017': ['2017'],
    'osmi_2018': ['2018'],
    'osmi_2019': ['2019'],
    'osmi_2020': ['2020'],
    'osmi_2021': ['2021'],
}